language: python
python: 2.7
cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.cache/lektor/builds
install: git clone https://$GH_TOKEN@github.com/rhysmoyne/creative-kids-dokuwiki.git && cd creative-kids-dokuwiki && ./travis-install.sh
script: echo 0
notifications:
  recipients:
    - rhys@creativekidssa.com.au
