language: python
python: 2.7
cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.cache/lektor/builds
install: git clone https://github.com/rhysmoyne/creative-kids-dokuwiki.git && cd creative-kids-dokuwiki && ./travis-install.sh
